create table if not exists public.island (
  id bigint generated by default as identity primary key,
  name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.island_profile (
  island_id bigint primary key references public.island(id) on delete cascade,
  island_name text not null default '',
  nickname text not null default '',
  representative_fruit text not null default '',
  representative_flower text not null default '',
  birthday text not null default '',
  hemisphere text not null default 'north',
  time_travel_enabled boolean not null default false,
  game_datetime text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.villager_state (
  island_id bigint not null references public.island(id) on delete cascade,
  villager_id text not null,
  liked boolean not null default false,
  on_island boolean not null default false,
  camping_visited boolean not null default false,
  former_resident boolean not null default false,
  island_order integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (island_id, villager_id)
);

create table if not exists public.catalog_state (
  island_id bigint not null references public.island(id) on delete cascade,
  catalog_type text not null,
  item_id text not null,
  owned boolean not null default false,
  donated boolean not null default false,
  quantity integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (island_id, catalog_type, item_id)
);

create table if not exists public.catalog_variation_state (
  island_id bigint not null references public.island(id) on delete cascade,
  catalog_type text not null,
  item_id text not null,
  variation_id text not null,
  owned boolean not null default false,
  quantity integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (island_id, catalog_type, item_id, variation_id)
);

create table if not exists public.calendar_entry (
  id bigint generated by default as identity primary key,
  island_id bigint not null references public.island(id) on delete cascade,
  visit_date text not null,
  npc_name text not null,
  note text not null default '',
  checked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_profile (
  id bigint generated by default as identity primary key,
  island_id bigint not null references public.island(id) on delete cascade,
  name text not null default '',
  birthday text not null default '',
  is_main boolean not null default false,
  is_sub boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
